module.exports={name:'help',aliases:['h','howto'],description:'Full command details — .help alone shows all commands, .help <command> shows detailed info',
async execute(sock,m,args){
    const p=global.BOT_PREFIX||'.';
    const wl=process.env.WARN_LIMIT||'3';
    const commands={
        ping:{cat:'📊 Status & Info',desc:"Check bot response speed, uptime, RAM, and CPU load in one message.",usage:p+'ping',al:'speed, latency, status'},
        alive:{cat:'📊 Status & Info',desc:'Confirm the bot is online and responding.',usage:p+'alive',al:'none'},
        uptime:{cat:'📊 Status & Info',desc:'Show how long the bot has been running since last restart.',usage:p+'uptime',al:'up'},
        stats:{cat:'📊 Status & Info',desc:'Full bot analytics: total messages tracked, active groups, unique users, AI status, RAM, and MongoDB connection status.',usage:p+'stats',al:'botstats, analytics, dashboard'},
        menu:{cat:'📊 Status & Info',desc:'Display the full command menu organised by category.',usage:p+'menu',al:'commands, list, cmds'},
        ai:{cat:'🤖 AI Assistant',desc:'Chat with XLICON AI (powered by Groq/Llama 3 — free). Remembers your conversation for 30 minutes.\n\nGet a FREE key at console.groq.com (no credit card needed), add GROQ_API_KEY to Railway.\n\nSub-commands:\n- '+p+'ai <question> — Ask anything\n- '+p+'ai on — Auto-reply to every message in this chat\n- '+p+'ai off — Stop auto-reply\n- '+p+'aiclear — Reset conversation memory\n\nWorks in personal and group chats.',usage:p+'ai Who is the richest person in Africa?\n'+p+'ai Tell me more about him\n'+p+'ai on\n'+p+'ai off\n'+p+'aiclear',al:'ask, claude, llm, bot'},
        imagine:{cat:'🤖 AI Assistant',desc:'Generate an AI image from text. Completely free, no API key needed.\n\nStyle prefixes: anime: realistic: cartoon: painting: sketch: watercolor: cinematic: pixel: fantasy: dark:\n\nTips: be descriptive, mention lighting, mood, setting and style for better results.',usage:p+'imagine a golden sunset over Lagos waterfront\n'+p+'imagine anime: cute girl with flowers\n'+p+'imagine realistic: lion in savanna\n'+p+'imagine cinematic: action hero in rain',al:'img, generate, draw, image, paint'},
        translate:{cat:'🤖 AI Assistant',desc:'Translate any text to any language. Reply to a message or type text directly. Uses AI (Groq) for best quality, falls back to MyMemory free API.\n\nLanguages: english french arabic yoruba igbo hausa spanish portuguese chinese japanese korean russian german italian turkish hindi swahili dutch zulu polish greek hebrew persian',usage:p+'translate arabic Hello how are you?\n'+p+'translate yoruba Good morning\n'+p+'translate french (reply to any message)',al:'tr, trans, lang'},
        summarize:{cat:'🤖 AI Assistant',desc:'Summarize a long message into 3-6 clear bullet points using AI. Reply to any long message or type text directly. Needs GROQ_API_KEY.',usage:p+'summarize (reply to a long message)',al:'tldr, summary, sum'},
        grammar:{cat:'🤖 AI Assistant',desc:'Fix grammar and spelling of any text using AI. Shows the corrected version and what was changed. Needs GROQ_API_KEY.',usage:p+'grammar I goes to market yesterday\n'+p+'grammar (reply to a message)',al:'fix, spell, correct, proofread'},
        anonread:{cat:'👻 Privacy & Stealth',desc:'Toggles ghost mode. When ON, the bot never sends read receipts — others only see grey ticks when they message you. One-way: you can still see blue ticks when others read your messages. Saved to MongoDB, survives restarts.',usage:p+'anonread (toggle ON)\n'+p+'anonread (toggle OFF)',al:'ghostmode, ghost, readanon'},
        anonview:{cat:'👻 Privacy & Stealth',desc:'Silently caches all status updates from contacts without sending a seen receipt. Files under 15MB saved to MongoDB (survive restarts), larger files kept in memory. Use .statusdl to retrieve them.',usage:p+'anonview (toggle ON/OFF)',al:'sv, statusview, viewstatus'},
        statusdl:{cat:'👻 Privacy & Stealth',desc:'Download cached statuses from a specific contact. Requires .anonview ON to cache statuses first.\n\nSub-commands:\n- list — See contacts with cached statuses\n- <number> — Get all their cached statuses\n- clear — Delete all cached statuses',usage:p+'statusdl list\n'+p+'statusdl 2348012345678\n'+p+'statusdl clear',al:'getstatus, vstatus'},
        antidelete:{cat:'👻 Privacy & Stealth',desc:'When ON, every message received is saved to MongoDB. If anyone deletes their message, the original is immediately forwarded to your DM. Covers groups and private chats. Survives restarts.',usage:p+'antidelete (toggle ON/OFF)',al:'ad, nodelete'},
        spy:{cat:'👻 Privacy & Stealth',desc:'Owner-only. Subscribe to a contact's online/offline status. Get a DM notification the moment they come online or go offline.\n\nSub-commands: add, list, remove',usage:p+'spy add 2348012345678\n'+p+'spy list\n'+p+'spy remove 1',al:'track, online, presence'},
        crypto:{cat:'🔍 Search & Info',desc:'Get live cryptocurrency price, 24h change, market cap, and 24h volume. No API key needed.\n\nShortcuts: btc, eth, bnb, sol, ada, xrp, doge, matic, shib, ton, trx, link, dot, usdt',usage:p+'crypto BTC\n'+p+'crypto ethereum\n'+p+'crypto solana',al:'coin, price, btc, eth'},
        movie:{cat:'🔍 Search & Info',desc:'Search for any movie or TV show: rating, cast, director, plot, genre, box office. Needs OMDB_API_KEY (free at omdbapi.com — no credit card).',usage:p+'movie Black Panther\n'+p+'movie Money Heist\n'+p+'movie The Lion King',al:'film, imdb, series, show'},
        weather:{cat:'🔍 Search & Info',desc:'Get live weather for any city — temperature, humidity, wind, condition.',usage:p+'weather Lagos\n'+p+'weather London UK',al:'w, forecast'},
        news:{cat:'🔍 Search & Info',desc:'BBC headlines by category.',usage:p+'news\n'+p+'news tech\n'+p+'news africa\n'+p+'news sport',al:'headlines'},
        github:{cat:'🔍 Search & Info',desc:'Look up any GitHub user — profile, bio, repo count, follower count, top starred repos. No API key needed.',usage:p+'github torvalds\n'+p+'github legacyhood',al:'ghprofile, gituser, gh'},
        lyrics:{cat:'🔍 Search & Info',desc:'Get song lyrics. Separate artist and title with a dash. No API key needed.',usage:p+'lyrics Wizkid - Essence\n'+p+'lyrics Burna Boy - Last Last\n'+p+'lyrics Davido - Fall',al:'song, lyric'},
        prayer:{cat:'🔍 Search & Info',desc:'Islamic prayer times for any city. All 5 daily prayers plus sunrise. No API key needed.',usage:p+'prayer Lagos Nigeria\n'+p+'prayer Cairo Egypt\n'+p+'prayer Dubai UAE',al:'salah, namaz, prayertime'},
        bible:{cat:'📖 Knowledge',desc:'Any Bible verse in the KJV translation. Supports single verses and ranges.\nExample books: John, Psalm, Romans, Genesis, Proverbs, Matthew, Revelation',usage:p+'bible John 3:16\n'+p+'bible Psalm 23:1\n'+p+'bible Proverbs 3:5-6',al:'verse, scripture, kjv'},
        quran:{cat:'📖 Knowledge',desc:'Any Quran verse with Arabic text and Sahih International English translation. Format: Surah:Ayah',usage:p+'quran 1:1  (Al-Fatiha)\n'+p+'quran 2:255  (Ayatul Kursi)\n'+p+'quran 112:1  (Al-Ikhlas)',al:'surah, ayah, quranverse'},
        fact:{cat:'📖 Knowledge',desc:'Random interesting fact. If GROQ_API_KEY is set, you can specify a category for topic-specific facts.',usage:p+'fact\n'+p+'fact science\n'+p+'fact history\n'+p+'fact space\n'+p+'fact animals',al:'facts, trivia, funfact'},
        horoscope:{cat:'📖 Knowledge',desc:'Daily horoscope for any star sign. Signs: aries taurus gemini cancer leo virgo libra scorpio sagittarius capricorn aquarius pisces',usage:p+'horoscope scorpio\n'+p+'horoscope leo\n'+p+'horoscope aquarius',al:'zodiac, star, starsign'},
        sticker:{cat:'🎨 Media & Stickers',desc:'Convert image or video to WhatsApp sticker. Optionally set pack name and author separated by |.',usage:p+'sticker  (reply to image or video)\n'+p+'sticker MyPack|AuthorName',al:'s, take, stkr'},
        watermark:{cat:'🎨 Media & Stickers',desc:'Add a text watermark to the bottom-right corner of any image. Reply to an image with this command.',usage:p+'watermark My Name  (reply to image)\n'+p+'watermark XLICON',al:'wm, addtext, stamp'},
        resize:{cat:'🎨 Media & Stickers',desc:'Resize an image to exact pixel dimensions. Reply to an image with the target size.',usage:p+'resize 800x600  (reply to image)\n'+p+'resize 1080x1080\n'+p+'resize 1280x720',al:'scale, imgsize, dimensions'},
        document:{cat:'🎨 Media & Stickers',desc:'Get file information from any media message: type, MIME type, file size, dimensions, duration, filename.',usage:p+'document  (reply to any media)',al:'fileinfo, mediainfo'},
        meme:{cat:'🎨 Media & Stickers',desc:'Fetch a random meme image from Reddit. No API key needed.',usage:p+'meme\n'+p+'meme funny\n'+p+'meme dankmemes',al:'memes, funnyimage, dank'},
        shorten:{cat:'🎨 Media & Stickers',desc:'Shorten any URL using the is.gd free API. No API key needed.',usage:p+'shorten https://www.example.com/very/long/url',al:'short, tinyurl, bitly'},
        quiz:{cat:'🎮 Games & Fun',desc:'Random multiple-choice trivia quiz. Reply .A, .B, .C, or .D within 30 seconds to answer.\n\nCategories: general film music science computers math sports geography history animals',usage:p+'quiz\n'+p+'quiz science\n'+p+'quiz geography',al:'trivia, qa'},
        tictactoe:{cat:'🎮 Games & Fun',desc:'Challenge a group member to Tic-Tac-Toe. Players take turns picking positions 1-9. Type .tt quit to forfeit.\n\nBoard positions:\n1 | 2 | 3\n4 | 5 | 6\n7 | 8 | 9',usage:p+'tictactoe @user  — challenge\n'+p+'tt 5  — pick center\n'+p+'tt quit  — forfeit',al:'ttt, tt, xo'},
        hangman:{cat:'🎮 Games & Fun',desc:'Classic hangman word game. Guess letters one at a time. 6 wrong guesses before game over.',usage:p+'hangman  — start game\n'+p+'hangman A  — guess a letter\n'+p+'hangman quit  — give up',al:'hm, wordgame'},
        riddle:{cat:'🎮 Games & Fun',desc:'Get a riddle to solve. Reply .answer to reveal the solution without giving away to others.',usage:p+'riddle  — get a riddle\n'+p+'riddle answer  — reveal solution',al:'puzzle, brainteaser'},
        roast:{cat:'🎮 Games & Fun',desc:'Send a fun roast from a curated list. For AI-generated custom roasts, use .airoast (needs GROQ_API_KEY).',usage:p+'roast @user\n'+p+'airoast @user  — AI roast',al:'dis, clown, burn, airoast'},
        todo:{cat:'⏰ Productivity',desc:'Personal to-do list saved per user in MongoDB. Add tasks, mark them done, and track progress.\n\nSub-commands: add, list, done <n>, remove <n>, clear',usage:p+'todo add Buy groceries\n'+p+'todo list\n'+p+'todo done 1\n'+p+'todo remove 2\n'+p+'todo clear',al:'task, tasks, checklist'},
        note:{cat:'⏰ Productivity',desc:'Save notes in groups (visible to all) or privately (sent to your DM).\n\nSub-commands: add <title> <text>, get <title>, list, delete <title>, clear\nPrivate: .note private add <title> <text>',usage:p+'note add rules Be respectful\n'+p+'note get rules\n'+p+'note list\n'+p+'note private add reminder Call mum',al:'notes, save, memo'},
        remind:{cat:'⏰ Productivity',desc:'Set a reminder. The bot messages you after the set time. Units: s=seconds, m=minutes, h=hours, d=days.',usage:p+'remind 30m Buy groceries\n'+p+'remind 2h Call doctor\n'+p+'remind 1d Happy birthday check',al:'reminder, remindme, timer'},
        contact:{cat:'⏰ Productivity',desc:'Generate a WhatsApp contact card (.vcf) from any user. The recipient can tap it to save to their phone contacts.',usage:p+'contact @user\n'+p+'contact  (reply to a message)',al:'vcard, savecontact'},
        admins:{cat:'👥 Group Admin',desc:'List all group admins. Owners marked separately from regular admins. Your entry marked with 👈 You, bot marked with 🤖.',usage:p+'admins',al:'adminlist, listadmins'},
        tagall:{cat:'👥 Group Admin',desc:'Mention all group members at once with an optional message above. Admin only.',usage:p+'tagall\n'+p+'tagall Please read the pinned message!',al:'everyone, all, mentionall'},
        kick:{cat:'👥 Group Admin',desc:'Remove a member from the group. Both you and the bot must be admins. Target by replying or mentioning.',usage:p+'kick @user\n'+p+'kick  (reply to message)',al:'remove, ban'},
        leaderboard:{cat:'👥 Group Admin',desc:'Show the top 10 most active members by message count. Counts start from when bot was added.\n\nPeriods: all (default), week, month',usage:p+'leaderboard\n'+p+'leaderboard week\n'+p+'leaderboard month',al:'lb, top, rank'},
        birthday:{cat:'👥 Group Admin',desc:'Track birthdays. Bot auto-wishes at 8am on the birthday. Works in any group the member is in.\n\nSub-commands: set DD/MM, list, remove',usage:p+'birthday set 25/12\n'+p+'birthday list\n'+p+'birthday remove',al:'bday, bd'},
        report:{cat:'👥 Group Admin',desc:'Report a member to all group admins with an optional reason. A report message is sent tagging all admins.',usage:p+'report @user Posting spam\n'+p+'report  (reply to a message)',al:'flag, reportuser'},
        antispam:{cat:'🛡️ Group Protection',desc:'Block spam messages. Members who send too many messages too fast get auto-warned and auto-kicked after '+wl+' warnings.',usage:p+'antispam on\n'+p+'antispam off',al:'as, spamprotect'},
        antilink:{cat:'🛡️ Group Protection',desc:'Block all URLs and WhatsApp group links from non-admins. Detects: http/https, wa.me, t.me, bit.ly, YouTube, and more.',usage:p+'antilink on\n'+p+'antilink off',al:'al, linkprotect, nolink'},
        antiforward:{cat:'🛡️ Group Protection',desc:'Block forwarded messages from non-admins. Any forwarded message is automatically deleted.',usage:p+'antiforward on\n'+p+'antiforward off',al:'noforward, blockforward'},
        antifake:{cat:'🛡️ Group Protection',desc:'When a new member joins with no profile picture, they are auto-kicked or warned. Set action to kick or warn.',usage:p+'antifake on\n'+p+'antifake off\n'+p+'antifake kick\n'+p+'antifake warn',al:'nobot, fakedetect'},
        lock:{cat:'🛡️ Group Protection',desc:'Block specific message types from non-admins.\n\nTypes: media, text, image, video, audio, sticker, doc, link, all, none\n\nSub: list, all, none, <type> on/off',usage:p+'lock image on\n'+p+'lock media on\n'+p+'lock link on\n'+p+'lock list\n'+p+'lock none',al:'lockchat, restrict'},
        slowmode:{cat:'🛡️ Group Protection',desc:'Enforce a cooldown between messages per member. If a member sends too fast, the message is deleted.',usage:p+'slowmode 30\n'+p+'slowmode 60\n'+p+'slowmode off',al:'slow, cooldown, ratelimit'},
        warn:{cat:'🛡️ Group Protection',desc:'Issue a warning to a member. After '+wl+' warnings they are auto-kicked and count resets.',usage:p+'warn @user\n'+p+'warn @user Posting inappropriate content',al:'warning'},
        autopost:{cat:'🤖 Auto Features',desc:'Schedule a message to be sent in this chat at the same time every day. Persists across Railway restarts.\n\nSub-commands: add HH:MM <message>, list, remove <n>, clear',usage:p+'autopost add 07:00 Good morning everyone! ☀️\n'+p+'autopost add 22:00 Good night everyone 🌙\n'+p+'autopost list\n'+p+'autopost remove 1',al:'schedule, autobroadcast'},
        autoreply:{cat:'🤖 Auto Features',desc:'Set keyword-based auto-replies. When someone sends a matching keyword, bot responds automatically.\n\nSub-commands: add keyword|reply, list, remove <keyword>, clear',usage:p+'autoreply add hi|Hello! How can I help?\n'+p+'autoreply list\n'+p+'autoreply remove hi',al:'ar, autorespond'},
        blacklist:{cat:'⚙️ Owner Only',desc:'Globally ban a number from using any bot command in any chat. Saved to MongoDB.\n\nSub-commands: add @user, add <number>, remove <number>, list',usage:p+'blacklist add @user\n'+p+'blacklist add 2348012345678\n'+p+'blacklist remove 2348012345678\n'+p+'blacklist list',al:'bl, ban, unban'},
        maintenance:{cat:'⚙️ Owner Only',desc:'Put the bot into maintenance mode. All non-owner commands are silently ignored. You can set a custom message.\n\nSub-commands: on, off, msg <text>',usage:p+'maintenance on\n'+p+'maintenance off\n'+p+'maintenance on Bot updating, back in 5 mins',al:'maint, offline'},
        prefix:{cat:'⚙️ Owner Only',desc:'Change the bot command prefix. Change is saved to MongoDB and survives restarts. 1-3 characters max.',usage:p+'prefix !\n'+p+'prefix /\n'+p+'prefix #',al:'setprefix, changeprefix'},
        backup:{cat:'⚙️ Owner Only',desc:'Export all bot settings (auto-replies, notes, todos, spy list, group settings, etc.) to a JSON file sent to your DM.',usage:p+'backup',al:'export, dumpdb'},
        setowner:{cat:'⚙️ Owner Only',desc:'Manage bot owner numbers from WhatsApp. Sub-commands: (no args)=show, add <number>, remove <number>, set <number>',usage:p+'setowner\n'+p+'setowner add 2348012345678\n'+p+'setowner remove 2348012345678',al:'owner, addowner'},
        broadcast:{cat:'⚙️ Owner Only',desc:'Send a message to every group the bot is in. Can broadcast text, images, or videos.',usage:p+'broadcast Hello everyone! 📢\n'+p+'broadcast  (reply to image)\n'+p+'broadcast list',al:'bc, announce'}
    };
    if(!args.length){
        const cats={};
        for(const[name,cmd] of Object.entries(commands)){if(!cats[cmd.cat])cats[cmd.cat]=[];cats[cmd.cat].push({name,cmd});}
        let txt='╭━━━━━━━━━━━━━━━━━━━━━━╮\n┃   📖 *XLICON COMMAND GUIDE*  ┃\n╰━━━━━━━━━━━━━━━━━━━━━━╯\n\n';
        txt+='Type *'+p+'help <command>* for full details, usage examples and aliases.\n\n';
        for(const[cat,cmds] of Object.entries(cats)){
            txt+='╭─── '+cat+' ───\n';
            for(const{name,cmd}of cmds) txt+='┃ *'+p+name+'* — '+cmd.desc.split('\n')[0].slice(0,68)+'\n';
            txt+='╰──────────────────────────\n\n';
        }
        txt+='> 🔤 Prefix: *'+p+'*  |  Warn limit: *'+wl+' warns = auto-kick*\n> Total commands: *'+Object.keys(commands).length+'*';
        return m.reply(txt);
    }
    const query=args[0].toLowerCase().replace(/^[.\/!]/,'');
    const aliasMap={};
    for(const[name,cmd]of Object.entries(commands)){
        (cmd.al||'').split(',').map(a=>a.trim()).filter(Boolean).forEach(a=>aliasMap[a]=name);
    }
    const key=commands[query]?query:aliasMap[query];
    if(!key) return m.reply('❌ No help entry for *'+p+query+'*\n\nUse *'+p+'help* to see all available commands.');
    const cmd=commands[key];
    await m.reply('╭━━━━━━━━━━━━━━━━━━━━━━╮\n┃   📖 *COMMAND DETAILS*   ┃\n╰━━━━━━━━━━━━━━━━━━━━━━╯\n\n🔹 *Command:* '+p+key+'\n🏷️ *Category:* '+cmd.cat+'\n\n📝 *Description:*\n'+cmd.desc+'\n\n📌 *Usage:*\n'+cmd.usage+'\n\n🔁 *Aliases:* '+cmd.al);
}};