/**
 * Image Generation Plugin — Pollinations.ai
 * Completely FREE, no API key needed whatsoever.
 * Generates AI images from text descriptions.
 */

const fetch = require('node-fetch');

module.exports = {
    name: 'imagine',
    aliases: ['img', 'generate', 'draw', 'image', 'paint'],
    description: 'Generate an AI image from a text description — completely free, no API key needed',

    async execute(sock, m, args) {
        const prompt = args.join(' ').trim();
        if (!prompt) {
            return m.reply(
`╭━━━━━━━━━━━━━━━━━━━╮
┃   🎨 *AI IMAGE GEN*  ┃
╰━━━━━━━━━━━━━━━━━━━╯

Generate any image with AI for free!

Usage: .imagine <description>

Examples:
- .imagine a golden sunset over Lagos
- .imagine futuristic city at night
- .imagine cute cat wearing sunglasses
- .imagine portrait of an African queen

Powered by Pollinations AI (free, no limits)`
            );
        }

        await m.react('⏳');
        await m.reply(`🎨 Generating: _"${prompt}"_\nPlease wait...`);

        try {
            // Pollinations.ai — completely free image generation
            const encoded = encodeURIComponent(prompt);
            const seed    = Math.floor(Math.random() * 999999);
            const url     = `https://image.pollinations.ai/prompt/${encoded}?width=1024&height=1024&seed=${seed}&nologo=true`;

            // Fetch the image buffer
            const res = await fetch(url, { timeout: 60000 });
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            const buffer = Buffer.from(await res.arrayBuffer());

            await sock.sendMessage(m.from, {
                image: buffer,
                caption: `🎨 *XLICON AI Image*\n\n📝 Prompt: _${prompt}_\n\n_Generated by Pollinations AI_`
            }, { quoted: m });

            await m.react('✅');
        } catch (e) {
            await m.react('❌');
            await m.reply('❌ Image generation failed: ' + e.message + '\n\nPlease try again with a different description.');
        }
    }
};
